services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory -disableTelemetry
    ports:
      - "8000:8000"

  seed:
    build:
      context: .
      target: app
    entrypoint: ["python", "docker/seed.py"]
    depends_on:
      - dynamodb
    env_file: .env
    restart: "no"

  api:
    build:
      context: .
      target: app
    depends_on:
      seed:
        condition: service_completed_successfully
    env_file: .env
    ports:
      - "9000:8080"

  refresh:
    build:
      context: .
      target: app
    command: ["src.refresh.lambda_handler"]
    depends_on:
      seed:
        condition: service_completed_successfully
    env_file: .env
    ports:
      - "9001:8080"
    profiles: ["refresh"]
