enum UnionState: String, CaseIterable {
  case AK = "Alaska"
  case AL = "Alabama"
  case AR = "Arkansas"
  case AZ = "Arizona"
  case CA = "California"
  case CO = "Colorado"
  case CT = "Connecticut"
  case DE = "Delaware"
  case FL = "Florida"
  case GA = "Georgia"
  case HI = "Hawaii"
  case IA = "Iowa"
  case ID = "Idaho"
  case IL = "Illinois"
  case IN = "Indiana"
  case KS = "Kansas"
  case KY = "Kentucky"
  case LA = "Louisiana"
  case MA = "Massachusetts"
  case MD = "Maryland"
  case ME = "Maine"
  case MI = "Michigan"
  case MN = "Minnesota"
  case MO = "Missouri"
  case MS = "Mississippi"
  case MT = "Montana"
  case NC = "North Carolina"
  case ND = "North Dakota"
  case NE = "Nebraska"
  case NH = "New Hampshire"
  case NJ = "New Jersey"
  case NM = "New Mexico"
  case NV = "Nevada"
  case NY = "New York"
  case OH = "Ohio"
  case OK = "Oklahoma"
  case OR = "Oregon"
  case PA = "Pennsylvania"
  case RI = "Rhode Island"
  case SC = "South Carolina"
  case SD = "South Dakota"
  case TN = "Tennessee"
  case TX = "Texas"
  case UT = "Utah"
  case VA = "Virginia"
  case VT = "Vermont"
  case WA = "Washington"
  case WI = "Wisconsin"
  case WV = "West Virginia"
  case WY = "Wyoming"

  var code: String {
    String(describing: self)
  }
}

extension UnionState {
  var capital: String {
    switch self {
    case .AK: return "Juneau"
    case .AL: return "Montgomery"
    case .AR: return "Little Rock"
    case .AZ: return "Phoenix"
    case .CA: return "Sacramento"
    case .CO: return "Denver"
    case .CT: return "Hartford"
    case .DE: return "Dover"
    case .FL: return "Tallahassee"
    case .GA: return "Atlanta"
    case .HI: return "Honolulu"
    case .IA: return "Des Moines"
    case .ID: return "Boise"
    case .IL: return "Springfield"
    case .IN: return "Indianapolis"
    case .KS: return "Topeka"
    case .KY: return "Frankfort"
    case .LA: return "Baton Rouge"
    case .MA: return "Boston"
    case .MD: return "Annapolis"
    case .ME: return "Augusta"
    case .MI: return "Lansing"
    case .MN: return "Saint Paul"
    case .MO: return "Jefferson City"
    case .MS: return "Jackson"
    case .MT: return "Helena"
    case .NC: return "Raleigh"
    case .ND: return "Bismarck"
    case .NE: return "Lincoln"
    case .NH: return "Concord"
    case .NJ: return "Trenton"
    case .NM: return "Santa Fe"
    case .NV: return "Carson City"
    case .NY: return "Albany"
    case .OH: return "Columbus"
    case .OK: return "Oklahoma City"
    case .OR: return "Salem"
    case .PA: return "Harrisburg"
    case .RI: return "Providence"
    case .SC: return "Columbia"
    case .SD: return "Pierre"
    case .TN: return "Nashville"
    case .TX: return "Austin"
    case .UT: return "Salt Lake City"
    case .VA: return "Richmond"
    case .VT: return "Montpelier"
    case .WA: return "Olympia"
    case .WI: return "Madison"
    case .WV: return "Charleston"
    case .WY: return "Cheyenne"
    }
  }
}
