enum UnionState: String, CaseIterable {
  case AK, AL, AR, AZ, CA, CO, CT, DE, FL, GA
  case HI, IA, ID, IL, IN, KS, KY, LA, MA, MD
  case ME, MI, MN, MO, MS, MT, NC, ND, NE, NH
  case NJ, NM, NV, NY, OH, OK, OR, PA, RI, SC
  case SD, TN, TX, UT, VA, VT, WA, WI, WV, WY
}

extension UnionState: CustomStringConvertible {
  var description: String {
    switch self {
    case .AK: return "Alaska"
    case .AL: return "Alabama"
    case .AR: return "Arkansas"
    case .AZ: return "Arizona"
    case .CA: return "California"
    case .CO: return "Colorado"
    case .CT: return "Connecticut"
    case .DE: return "Delaware"
    case .FL: return "Florida"
    case .GA: return "Georgia"
    case .HI: return "Hawaii"
    case .IA: return "Iowa"
    case .ID: return "Idaho"
    case .IL: return "Illinois"
    case .IN: return "Indiana"
    case .KS: return "Kansas"
    case .KY: return "Kentucky"
    case .LA: return "Louisiana"
    case .MA: return "Massachusetts"
    case .MD: return "Maryland"
    case .ME: return "Maine"
    case .MI: return "Michigan"
    case .MN: return "Minnesota"
    case .MO: return "Missouri"
    case .MS: return "Mississippi"
    case .MT: return "Montana"
    case .NC: return "North Carolina"
    case .ND: return "North Dakota"
    case .NE: return "Nebraska"
    case .NH: return "New Hampshire"
    case .NJ: return "New Jersey"
    case .NM: return "New Mexico"
    case .NV: return "Nevada"
    case .NY: return "New York"
    case .OH: return "Ohio"
    case .OK: return "Oklahoma"
    case .OR: return "Oregon"
    case .PA: return "Pennsylvania"
    case .RI: return "Rhode Island"
    case .SC: return "South Carolina"
    case .SD: return "South Dakota"
    case .TN: return "Tennessee"
    case .TX: return "Texas"
    case .UT: return "Utah"
    case .VA: return "Virginia"
    case .VT: return "Vermont"
    case .WA: return "Washington"
    case .WI: return "Wisconsin"
    case .WV: return "West Virginia"
    case .WY: return "Wyoming"
    }
  }
}

extension UnionState {
  var capital: String {
    switch self {
    case .AK: return "Juneau"
    case .AL: return "Montgomery"
    case .AR: return "Little Rock"
    case .AZ: return "Phoenix"
    case .CA: return "Sacramento"
    case .CO: return "Denver"
    case .CT: return "Hartford"
    case .DE: return "Dover"
    case .FL: return "Tallahassee"
    case .GA: return "Atlanta"
    case .HI: return "Honolulu"
    case .IA: return "Des Moines"
    case .ID: return "Boise"
    case .IL: return "Springfield"
    case .IN: return "Indianapolis"
    case .KS: return "Topeka"
    case .KY: return "Frankfort"
    case .LA: return "Baton Rouge"
    case .MA: return "Boston"
    case .MD: return "Annapolis"
    case .ME: return "Augusta"
    case .MI: return "Lansing"
    case .MN: return "Saint Paul"
    case .MO: return "Jefferson City"
    case .MS: return "Jackson"
    case .MT: return "Helena"
    case .NC: return "Raleigh"
    case .ND: return "Bismarck"
    case .NE: return "Lincoln"
    case .NH: return "Concord"
    case .NJ: return "Trenton"
    case .NM: return "Santa Fe"
    case .NV: return "Carson City"
    case .NY: return "Albany"
    case .OH: return "Columbus"
    case .OK: return "Oklahoma City"
    case .OR: return "Salem"
    case .PA: return "Harrisburg"
    case .RI: return "Providence"
    case .SC: return "Columbia"
    case .SD: return "Pierre"
    case .TN: return "Nashville"
    case .TX: return "Austin"
    case .UT: return "Salt Lake City"
    case .VA: return "Richmond"
    case .VT: return "Montpelier"
    case .WA: return "Olympia"
    case .WI: return "Madison"
    case .WV: return "Charleston"
    case .WY: return "Cheyenne"
    }
  }
}
